# Abreviaturas y siglas {.unnumbered}

**ANEP** Administración Nacional de Educación Pública

**ASSE** Administración de Servicios de Salud del Estado

**CBE** Casa de Breve Estadía

**CCZ** Centro Comunal Zonal

**CEDAW** Convención para la Eliminación de todas las formas de Discriminación contra la Mujer

**CEPAL** Comisión Económica para América Latina y el Caribe

**CET** Centro de Estadía Transitoria

**CMC** Centro de Medio Camino

**CNCLVD** Consejo Nacional Consultivo de Lucha contra la Violencia Doméstica

**CNCVBG** Consejo Nacional Consultivo por una Vida Libre de Violencia de Género hacia las
Mujeres

**CNG** Consejo Nacional de Género

**CONAPRO** Concertación Nacional Programática

**DAT** Dispositivos de Articulación Territorial

**ECH** Encuesta Continua de Hogares

**EF** Espacio Feminista

**ETM** Equipo Territorial de Montevideo

**EVBGG** Encuesta de Violencia Basada en Género y Generaciones

**FGN** Fiscalía General de la Nación

**FU** Feminicidios Uruguay

**GED** Género en el Desarrollo

**GRECMU** Grupo de Estudios sobre la Condición de la Mujer Uruguaya

**IM** Intendencia de Montevideo

**INAU** Instituto del Niño, Niña y Adolescente del Uruguay

**INE** Instituto Nacional de Estadística

**Inmujeres** Instituto Nacional de las Mujeres

**IPP** Incidencia de la Pobreza en Personas

**MCO** Mínimos Cuadrados Ordinarios

**MEC** Ministerio de Educación y Cultura

**MED** Mujeres en el Desarrollo

**MI** Ministerio del Interior

**MIDES** Ministerio de Desarrollo Social

**MSP** Ministerio de Salud Pública

**NBI** Necesidades Básicas Insatisfechas

**OIG** Observatorio de Igualdad de Género

**ONG** Organizaciones No Gubernamentales

**OSC** Organizaciones de la Sociedad Civil

**OVBG** Observatorio de Violencia Basada en Género

**PLEMUU** Plenaria de Mujeres Uruguayas

**PIODNA** Plan de Igualdad de Oportunidades y Derechos

**RUCVDS** Red Uruguaya contra la Violencia Doméstica y Sexual

**SIG** Sistema de Información de Género

**SIPPAU** Sistema de Información del Proceso Penal Acusatorio de Uruguay

**SIPIAV** Sistema Integrado de Protección a la Infancia y Adolescencia contra la Violencia

**SGSP** Sistema de Gestión de Seguridad Pública

**SMART** Sistema de Monitoreo de Articulación Territorial

**SNIS** Sistema Nacional Integrado de Salud

**SRI** Sistema de Respuesta Integral

**TF** Tasa de feminicidios

**UEVD** Unidades Especializadas en Violencia Doméstica

**UEVDG** Unidades Especializadas en Violencia Doméstica y de Género

**VBG** Violencia Basada en Género

**VD** Violencia Doméstica