# Caracterización de la política pública de combate a la VBG


En este capítulo se presenta el marco normativo sobre la VBG y se analiza la política
pública para su combate. Esta política está conformada por acciones, planes y programas
desarrollados por diferentes instituciones del Estado, tanto a nivel nacional como departamental, y tiene como organismo rector al Inmujeres. Primero se examina el marco normativo, los planes y programas para estudiar el enfoque teórico-metodológico de la política. Luego se presentan las acciones, servicios y dispositivos existentes en cada una de las etapas relevantes de la política: prevención, atención, protección y salida de las situaciones de VBG. Se analiza el alcance que estos tienen y se da cuenta del sistema de información que permite el monitoreo y evaluación de cada uno de los componentes. Finalmente, se problematiza sobre la cobertura de la política pública analizada y se plantean los principales resultados de la evaluación externa realizada al Plan 2016-2019 por la consultora DINAMIA.

## Marco normativo, planes y enfoque de la política pública

El marco normativo vigente en materia de VBG contiene, además de la Ley 17.514 de
Violencia Doméstica desarrollada en el Capítulo 2, tres leyes recientes^[Además está vigente la Ley 17815 de Violencia Sexual contra Niños, Adolescentes e Incapaces de 2004, la que no se abordará en esta investigación.]: la Ley 19.580 de “Violencia Hacia las Mujeres Basada en Género” promulgada en diciembre de 2017, la Ley 19.538 de “Actos de discriminación y femicidio” promulgada en octubre de ese mismo año y la Ley 19.643 de “Prevención y Combate de la trata de personas” de agosto de 2018. Dado que las víctimas de trata y, en particular, la trata con fines de explotación sexual son en su mayoría mujeres y niñas, la Ley de Trata resulta específica para combatir un tipo de violencia basada en género.

La Ley 19.580 dispone una serie de medidas en diversas áreas tales como la educación,
salud, trabajo, vivienda, entre otras. A su vez, prevé diferentes mecanismos de atención a
varones violentos. La Ley busca garantizar el efectivo goce del derecho de las mujeres a una vida libre de violencia basada en género, comprendiendo a mujeres de todas las edades, a mujeres cis-género y mujeres trans, cualquiera sea su orientación sexual, situación socioeconómica, pertenencia territorial, creencia, origen cultural y étnico-racial o situación de discapacidad (Art.1). Para ello, se establecen medidas integrales de prevención, atención, protección, sanción y reparación.

Esta Ley concibe a la VBG como toda conducta que, sustentada en una relación desigual
de poder en base al género, busque menoscabar o anular el goce o ejercicio de los derechos
humanos de las mujeres. Se incluyen no solo las acciones de particulares, sino también del
propio Estado (Art. 4). Por otro lado, en el Art. 6 de la ley se establecen las diferentes
manifestaciones de violencia basada en género, detalladas a continuación:

    > - Violencia física. Toda acción, omisión o patrón de conducta que dañe la integridad corporal de una mujer.
    - Violencia psicológica o emocional. Toda acción, omisión o patrón de conducta dirigido a perturbar, degradar o controlar la conducta, el comportamiento, las creencias o las decisiones de una mujer, mediante la humillación, intimidación, aislamiento o cualquier otro medio que afecte su estabilidad psicológica o emocional. 
    - Violencia sexual. Toda acción que implique la vulneración del derecho de una mujer a decidir voluntariamente sobre su vida sexual o reproductiva, a través de amenazas, coerción, uso de la fuerza o intimidación, incluyendo la violación dentro del matrimonio y de otras relaciones vinculares o de parentesco, exista o no convivencia, la transmisión intencional de infecciones de transmisión sexual, así como la prostitución forzada y la trata sexual.
    - Violencia económica. Toda conducta dirigida a limitar, controlar o impedir ingresos económicos de una mujer, incluso el no pago contumaz de las obligaciones alimentarias, con el fin de menoscabar su autonomía. 
    - Violencia patrimonial. Toda conducta dirigida a afectar la libre disposición del patrimonio de una mujer, mediante la sustracción, destrucción, distracción, daño, pérdida, limitación o retención de objetos, documentos personales, instrumentos de trabajo, bienes, valores y derechos patrimoniales. 
    - Violencia simbólica. Es la ejercida a través de mensajes, valores, símbolos, íconos, imágenes, signos e imposiciones sociales, económicas, políticas, culturales y de creencias religiosas que transmiten, reproducen y consolidan relaciones de dominación, exclusión, desigualdad y discriminación, que contribuyen a naturalizar la subordinación de las mujeres.  
    - Violencia femicida. Es la acción de extrema violencia que atenta contra el derecho fundamental a la vida y causa la muerte de una mujer por el hecho de serlo, o la de sus hijas, hijos u otras personas a su cargo, con el propósito de causarle sufrimiento o daño.  - Violencia por prejuicio hacia la orientación sexual, identidad de género o expresión de género. Es aquella que tiene como objetivo reprimir y sancionar a quienes no cumplen las normas tradicionales de género, sea por su orientación sexual, identidad de género o expresión de género (Art. 6, Ley 19580).
    

Se incluyen además la violencia obstétrica, la violencia laboral, la violencia en el ámbito
educativo, el acoso sexual callejero, la violencia política, la violencia mediática, la violencia comunitaria, la violencia institucional y la violencia étnico-racial.

Se define al Inmujeres como el órgano rector de las políticas públicas de combate a la
VBG, responsable de la promoción, diseño, coordinación, articulación, seguimiento y evaluación de las políticas (Art. 11). A su vez, se reemplaza al CNCLVD por el Consejo Nacional Consultivo por una Vida Libre de Violencia de Género hacia las Mujeres (CNCVBG) y se crea el Observatorio sobre Violencia Basada en Género hacia las Mujeres (OVBG), destinado al monitoreo, recolección, producción, registro y sistematización de datos sobre VBG. Su composición se define de carácter interinstitucional, con participación de la Oficina de Planeamiento y Presupuesto, el MI, el Inmujeres y la RUCVDS (Art. 12).

Por otro lado, la Ley 19.538 modifica los artículos 311 y 312 del Código Penal,
relacionados con actos de discriminación y femicidio. El Art. 3 de dicha ley, incorpora el
numeral 8 al Art. 312 del Código Penal, el femicidio como una agravante muy especial al delito de homicidio al que aplica la pena de penitenciaría de quince a treinta años. En estos términos el femicidio es considerado como el homicidio de una mujer por motivos de odio, desprecio o menosprecio, por su condición femenina (Morelli, 2018).


En el Art. 3, la norma dispone tres presunciones simples de existencia del móvil de odio,
desprecio o menosprecio, aunque pudieran existir otras:

    > a) A la muerte le hubiera precedido algún incidente de violencia física, psicológica, sexual, económica o de otro tipo, cometido por el autor contra la mujer, independientemente de que el hecho haya sido denunciado o no por la víctima.  
    b) La víctima se hubiera negado a establecer o reanudar con el autor una relación de pareja, enamoramiento, afectividad o intimidad.  
    c) Previo a la muerte de la mujer el autor hubiera cometido contra ella cualquier conducta que atente contra su libertad sexual (Art. 3, Ley 19538).


En el caso de la presunción a), la existencia de violencia previa no debe ser analizado
únicamente en los casos que entre la víctima y el femicida exista una relación de pareja o
familiar. Es decir, que no debe acotarse a los femicidios íntimos y familiares para constituir un femicidio (Morelli, 2018).

Por otro lado, la Ley 19.643 tiene por objeto la prevención, persecución y sanción de la
trata y la explotación de personas, así como la atención, protección y reparación de las víctimas. La trata de personas se define como la captación, el traslado y la recepción de personas dentro de un país o a través de fronteras que puede tener como fines la explotación sexual comercial, el trabajo forzado, entre otros. Como ya se mencionó, una de las expresiones más comunes de la trata es aquella con fines de explotación sexual y donde las principales víctimas son las mujeres y niñas.

Respecto a la política pública que aborda el problema de la VBG, en noviembre de 2015
se aprobó el “Plan de Acción: por una vida libre de violencia de género, con mirada generacional 2016-2019”, a través del Decreto 306/015 del Poder Ejecutivo^[Existen otros planes de combate a la VBG que se profundizarán en esta investigación: el II Plan
Nacional para la Erradicación de la Explotación Sexual de Niñas, Niños y Adolescentes 2016-2021 y el Plan Nacional de Acción para la Prevención y Combate a la Trata de Personas 2018-2020.]. Este plan fue concebido por el CNCLVD y, por ende, participaron instituciones del Estado y la RUCVDS representando a las organizaciones de la sociedad civil. Recoge una visión integral de la VBG y un abordaje interdisciplinario e intersectorial (Dinamia, 2020). El Plan, busca consolidar una política pública nacional para prevenir, enfrentar y reducir la VBG en todo el territorio nacional así como también reparar a sus víctimas. Como resultados esperados tiene la disminución de los femicidios en general y los asociados a la violencia doméstica, así como la reducción de la cantidad de mujeres que experimenten algún tipo de VBG (CNCLCVD, 2016). 

Para alcanzar esos resultados, se establece como objetivo específico “consolidar la
implementación de un sistema interinstitucional de respuesta a la violencia basada en género, que incluya la articulación entre la prevención, el acceso a la justicia, la atención y protección de las víctimas, la sanción a las personas agresoras y la restitución de derechos” (CNCLCVD, 2016, p. 51). El sistema de respuesta integral se orienta hacia mujeres de todas las edades, desde la infancia hasta la vejez.

Otro objetivo específico del Plan es promover pautas de relacionamiento entre mujeres y
varones, sustentadas en patrones no violentos para contribuir a la modificación del modelo
cultural hegemónico. Para poder medir los resultados del Plan, otro objetivo establece avanzar hacia la construcción de un sistema de información integral que permita visualizar, monitorear y dar seguimiento de los diferentes indicadores relacionados con la violencia basada en género. Así, se plantea construir un sistema de información institucional que permita obtener información oportuna y de calidad sobre la VBG en todo el país.

La política del Plan se enmarca en un enfoque de política de Género en el Desarrollo
(GED)^[GED es un enfoque con perspectiva de género y, por lo tanto, se diseñan políticas para transformar las relaciones jerárquicas de género y cuestionar la división sexual del trabajo. Busca romper con la asimetría de poder entre hombres y mujeres, a la vez, que dirige sus políticas tanto a mujeres como a varones. A diferencia del enfoque de Mujeres en el Desarrollo (MED) donde el papel socialmente asignado a los hombres no es cuestionado como tampoco se cuestiona la desigual relación de poder entre hombres y mujeres (Rodríguez Gustá, 2008).], en la medida que promueve servicios y programas para atender a las mujeres víctimas de VBG, así como también trabajar en la resocialización de los varones violentos. Por lo tanto, se enfoca en las desigualdades de género y en los problemas inherentes a las relaciones jerárquicas de género, características que Moser (1995) plantea son propias del enfoque GED. Concentrarse en el ‘género’ en lugar de en la ‘mujer’ permite quitar el foco en el sexo, es decir, en las diferencias biológicas entre hombres y mujeres para ponerlo en el género, esto es, en la relación social entre hombres y mujeres, en la cual la mujer ha estado sistemáticamente subordinada (Moser, 1995).

Asimismo, el Plan establece la sensibilización y capacitación de las/los operadores
jurídicas/os, de seguridad, psico-sociales, de la educación, de la salud y de comunicación, tanto públicos como privados, en la temática de la VBG de manera que sean capaces de brindar una atención integral con énfasis en la no revictimización de las mujeres. A través del Plan se reconoce que las instituciones no son neutrales al género, sino por el contrario reproducen las desigualdades y el poder masculino, por lo que resulta imprescindible que estas instituciones reflejen genuinamente los intereses de las mujeres y reconozcan las desigualdades preexistentes para alcanzar la igualdad de género (Valdés, 2006). El cumplimiento del Plan requiere de un esfuerzo de institucionalizar la perspectiva de género que abarque desde un principio a todo el personal de las organizaciones, que implique la sensibilización en género que se traduzca en sus prácticas, la incorporación de un lenguaje no sexista e inclusivo y el respeto a todas las personas en su diversidad. Esto permitirá cambiar las reglas formales e informales, las normas y los procesos institucionales (Buendía, 2016).

Finalmente, las medidas tendientes a producir un cambio cultural en la sociedad promoviendo nuevas formas de relacionamiento entre varones y mujeres, buscan cubrir los intereses estratégicos^[Este concepto junto al de necesidades prácticas fueron desarrollados por Molyneaux (1985) e introducidos por Moser (1993) al discurso político del desarrollo con perspectiva de género.] de las mujeres en la medida que apuntan a un cambio estructural que transforme las relaciones de género.

### Programas, servicios, dispositivos y sistemas de información

En este apartado se analizan los diferentes componentes del Sistema de Respuesta
Interinstitucional (SRI), que como tal funciona desde 2018 a partir de la promulgación de la Ley 19.580^[Varios de los componentes existen desde antes de 2018.]. El SRI tiene como cometido la prevención y detección oportuna, atención, protección y acceso a la justicia de niñas, niños, adolescentes y mujeres que viven situaciones de VBG. Así como también, la reparación a las víctimas y la resocialización de los varones violentos (CNC, 2020). Las instituciones que lo componen son: Inmujeres, Ministerio del Interior, Fiscalía General de la Nación, Intendencia de Montevideo, Instituto del Niño, Niña y Adolescente del Uruguay, Ministerio de Salud Pública y Poder Judicial.

Cada institución es responsable de brindar respuestas según su competencia y de acuerdo
con las disposiciones legales y las políticas formuladas por el Inmujeres, en su calidad de
organismo rector de las políticas de género (CNC, 2020). El SRI incluye las acciones de
prevención, sensibilización y promoción de derechos, los servicios de atención a mujeres, los servicios de rehabilitación de varones, los servicios y medidas de protección a mujeres y sus hijas/os y el acceso al sistema de justicia así como también los programas de salida de las situaciones de VBG. Asimismo, cada institución posee un sistema de información que permite el monitoreo de las diferentes situaciones y derivaciones correspondientes.

## Prevención, sensibilización y promoción de derechos


Las acciones de prevención y promoción de derechos, en general, están enfocadas en la
infancia y la adolescencia (CNCLCVD, 2016). En este sentido, desde 2016 funciona el Programa de formación en educación para la igualdad y no discriminación entre mujeres y varones, coordinado por un equipo interinstitucional con representantes del MEC, la Administración Nacional de Educación Primaria (ANEP), el Inmujeres y el Plan Ceibal (CNC, 2020).

Respecto a las acciones de sensibilización se destacan diversas campañas. La campaña
impulsada por el Inmujeres, “Noviazgos Libres de Violencia”, se desarrolla en todo el país desde 2015 con la participación de adolescentes y educadoras/es. Se establecen 50 días de reflexión, sensibilización y promoción de noviazgos libres de violencia, para lo cual, se trabaja en conjunto con diversas instituciones públicas y privadas, organizaciones comunitarias y medios de prensa de cada uno de los departamentos del país (Inmujeres, 2018).

Se realizaron otras campañas puntuales como la campaña de bien público denominada “Rompamos el Silencio”, aprobada por Presidencia de la República y elaborada por la RUCVDS que a través de un spot audiovisual y dos spot radiales, buscó ayudar a desnaturalizar la VBG. A su vez, fue realizada la campaña “Pelota al medio a la esperanza” del MI y la ONG Gurises Unidos, dirigida a niñas, niños y adolescentes con el objetivo de sensibilizar, a través del juego, sobre las relaciones libres de violencia. En la misma línea, se elaboró la campaña ‘Libre de Violencias’ del Instituto del Niño, Niña y Adolescente del Uruguay (INAU) que trabajó el tema mediante una exposición de fotos y talleres con niñas, niños y adolescentes. Por otro lado, se generó la campaña “Montevideo ciudad libre de acoso” con el objetivo de instalar el tema del acoso callejero como un problema social. En el marco de la difusión de la Ley de Trata se realizó la campaña “Uruguay Libre de Trata”, orientada a sensibilizar sobre la trata de personas con fines de explotación sexual. Por último, se realizó la Muestra Itinerante sobre Violencia Basada en Género a cargo del MEC, Inmujeres, CNG y la Dirección Nacional de Impresiones y Publicaciones Oficiales (IMPO) exhibida en todo el país (CNC, 2020).

El alcance de estas campañas aún sigue siendo acotado, por ejemplo, la cuarta edición de
la campaña ‘Noviazgos Libres de Violencia’ alcanzó a 14.500 adolescentes y 1.450 referentes (CNC, 2020). Mientras que la campaña de sensibilización a cargo de la RUCVDS se estima alcanzó a 118.000 personas (Dinamia, 2020). Según se desprende de la evaluación de Dinamia (2020), si bien las acciones de información y sensibilización están alineadas con el objetivo de cambio cultural que implica reconocer la dimensión estructural de la violencia de género, las acciones y programas no tienen un carácter sistemático ni están coordinados ni tienen en muchos casos un alcance nacional. Tampoco tienen en cuenta dónde ocurren los feminicidios ni quiénes son las mujeres más afectadas. Por lo tanto, es cuestionable el impacto que estas acciones pueden tener para producir cambios profundos y de alcance masivo.

### Atención a mujeres en situación de VBG

El Inmujeres, es el organismo rector de las políticas de género y por tanto, parte central
del SRI, en tanto diseña e implementa, una Red de Servicios de Atención a la Violencia Basada en Género. Esta red funciona en convenio con organizaciones de la sociedad civil (OSC) bajo la supervisión de un equipo perteneciente al Departamento de Violencia Basada en Género del Inmujeres. Para los diferentes momentos del proceso de salida de una situación de violencia, se habilitan dispositivos específicos, los Servicios de Atención del Inmujeres, no sólo están dirigidos a mujeres en situación de VBG, sino también, a varones agresores que quieren dejar de serlo (Inmujeres, s.d.).

Los servicios de atención a mujeres brindan asistencia psico-social y jurídica a mayores
de 18 años en situación de VBG. Adicionalmente, los servicios del interior del país ofrecen patrocinio en juicio. Los equipos están integrados generalmente por profesionales de la psicología, el trabajo social, la abogacía, procuraduría y secretaría (Inmujeres, 2016). Esta conformación permite un abordaje interdisciplinar e integral de las situaciones de las mujeres que consultan por VBG. Actualmente, el Inmujeres cuenta con 33 servicios distribuidos en diferentes localidades del país, teniendo presencia en todos los departamentos (Inmujeres, 2016). 

Los servicios cuentan con un Protocolo único de Atención^[Además del protocolo de Inmujeres, las restantes instituciones del CNC tienen uno propio (Ver Anexo). A partir
del CNC se ha trabajado en la construcción de un marco conceptual común para el abordaje de la VBG desde una perspectiva de género, generaciones, derechos humanos, discapacidad, etnia-raza y diversidad sexual, que brinde orientaciones claras y coherentes para la intervención especializada que contribuya a alcanzar cada vez mejores niveles de calidad de la respuesta (Inmujeres, s.d.). Otras instituciones del SRI tienen su propio protocolo de abordaje a las situaciones de VBG, varios de estos fueron revisados y actualizados en 2019: Protocolo de actuación en situaciones de violencia basada en género de Inmujeres; Protocolo para el abordaje de situaciones de violencia sexual hacía, niñas, niños y adolescentes en el marco del Sistema Nacional Integrado de Salud; Protocolo para el
abordaje de situaciones de maltrato a niñas, niños y adolescentes en el marco del Sistema Nacional Integrado de Salud; Protocolo de detección e investigación en trata, tráfico y explotación de personas, del Ministerio del Interior y Fiscalía General de la Nación; Protocolo de Actuación Policial, Detección e Investigación de Trata, Tráfico y Explotación de Personas; y Protocolo de Detección e Investigación en Explotación Sexual Comercial de Niñas, Niños y Adolescentes, del Ministerio del Interior; Protocolo de actuación de los servicios de atención a mujeres en situación de violencia basada en género de la Comuna Mujer, de la Asesoría para la Igualdad de Género de la Intendencia de Montevideo. A su vez, se está actualizando el Protocolo de detección y abordaje de los casos de violencias en ANEP (CNC, 2020).] que representa una guía para enmarcar el trabajo, contribuyendo a unificar criterios a la hora de abordar las diferentes situaciones. El protocolo define que la información sobre las consultantes se recabe en una ficha de registro que luego se reporta al Sistema de Información en Género (SIG) del Inmujeres (Inmujeres, 2016).

Además de los servicios de atención a mujeres, el sistema de respuesta del Inmujeres
cuenta con un equipo de carácter móvil en cada departamento del país: 18 Dispositivos de
Articulación Territorial (DAT), uno por cada departamento del interior y un Equipo Territorial en Montevideo (ETM). Estos equipos complementan el trabajo de los servicios, mediante la difusión y comunicación de la atención que ofrecen los servicios en el territorio a través de distintas vías (folletería, capacitaciones, talleres, etc.). En la medida que estos dispositivos identifican situaciones de VBG pueden realizar una atención primaria y luego derivar a los servicios. De esta manera los DAT y el ETM tienen una función más proactiva e intentan llegar a zonas donde residen mujeres que ignoran la existencia de los servicios o no tienen facilidades para acceder a éstos (DINEM, 2014).

Respecto a la atención a mujeres en situación de trata con fines de explotación sexual, el
Inmujeres dirige dos servicios específicos, uno ubicado en Cerro Largo y otro en Montevideo. El servicio de Montevideo cuenta con un equipo con más carga horaria en relación con el de Cerro Largo, y por lo tanto, brinda una mayor cobertura alcanzando a los departamentos de San José, Canelones, Maldonado, Rocha, Lavalleja y Florida (CNC, 2020). Estos servicios brindan atención y asistencia psico-social, legal y de patrocinio en juicio, a mujeres que sufren o han sufrido situaciones de trata con fines de explotación sexual comercial, desde un enfoque integral. Asimismo, atienden a familiares y personas allegadas a las mujeres en situaciones de trata. Los equipos cuentan con profesionales de tres áreas: psicología, trabajo social y derecho (Inmujeres, 2016).

El Inmujeres en convenio con la Intendencia de Montevideo (IM), brinda un Servicio de
Orientación Telefónica, gratuito de alcance nacional y disponible los 365 días del año^[El número 0800 4141 para teléfonos fijos y el *4141 para celulares.]. El servicio es confidencial y anónimo, ya que la llamada desde línea fija no queda registrada en la factura telefónica. Esta red de servicios de atención, perteneciente al Inmujeres, se complementa con dispositivos dependientes de otros organismos que conforman el Sistema Interinstitucional de Respuesta Integral a la Violencia Basada en Género.

La IM, a través del programa Comuna Mujer, creado en 1996, atiende a mujeres en situación de VBG en 11 zonas de Montevideo, brindando asesoramiento jurídico y psico-social. Adicionalmente, la IM dispone de un servicio de atención a varones que ejercen o han ejercido violencia de género en las relaciones sexo-afectivas (CNC, 2020; Dinamia, 2020).

La atención a niñas, niños y adolescentes está a cargo del INAU a través del Sistema
Integral de Protección a la Infancia y la Adolescencia (SIPIAV). Cuenta con 33 Comités de Recepción Local y referentes de violencia en los 19 departamentos. Estos servicios brindan
atención para prevenir el maltrato y abuso sexual infantil y adolescente. A su vez, cuenta con siete centros de referencia regionales que se ubican en Montevideo (3), Canelones (2), Soriano (1) y Colonia (1). Por otro lado, también dispone de una línea telefónica exclusiva para recibir consultas, la Línea Azul 0800-5050 (CNC, 2020).

Para radicar denuncias de situaciones de violencia de género como por ejemplo: violencia
doméstica, violencia sexual, maltrato, abuso sexual hacia niñas, niños y adolescentes, y
situaciones de discriminación se encuentran las UEVDG del MI. En total son 56 UEVDG que se
distribuyen en los 19 departamentos del país (CNC, 2020). Los mecanismos de denuncia de
situaciones de VBG se han ampliado, en este sentido, además de las denuncias presenciales en las Comisarías, las UEVDG y otras dependencias policiales, se sumaron mecanismos no
presenciales a través de la APP 911, el 0800-5000 y la denuncia on-line a través de la página web del ministerio (Gularte et al., 2020). El MI también cuenta con un servicio de atención a varones ofensores y a víctimas de violencia doméstica y de género para el personal policial con cobertura nacional (CNC, 2020).

Por otro lado, el Ministerio de Defensa también cuenta con un equipo que atiende situaciones de Violencia Doméstica centralizado en la Dirección Nacional de Sanidad de las Fuerzas Armadas Montevideo, contando con equipos de referencia en cada una de las Fuerzas Armada, Aérea y Ejército (CNC, 2020).

La FGN actualmente cuenta con 5 Fiscalías de Delitos Sexuales, Violencia Doméstica y
Violencia Basada en Género. También tiene una Unidad de Víctimas y Testigos que brinda
información, asistencia y acompañamiento a las víctimas y testigos involucradas/os en
situaciones de violencia de género (CNC, 2020).

Como se adelantó en el capítulo 2, un actor clave en la detección de situaciones de VBG
es el MSP a través de las instituciones que integran el SNIS, es decir, la Administración de Servicios de Salud del Estado (ASSE) y las instituciones de salud privadas. A través del SNIS, el MSP cuenta con equipos de Referencia en Violencia Basada en Género en todos los prestadores de salud, tanto públicos como privados. El MSP establece metas a las instituciones prestadoras para garantizar la atención y cobertura en materia de violencia de género y generaciones, esto implica que las instituciones que cumplen las metas reciben un aporte económico para asegurar su cumplimiento (CNC, 2020).

La evaluación del Plan realizada por Dinamia (2020) muestra que el SRI en gran medida
está orientado a la atención de la VBG en la pareja y ex-pareja, dejando fuera otras
manifestaciones de la VBG. A su vez, se observa que los componentes del SRI trabajan en
mayor medida sobre las consecuencias de la VBG y no tanto sobre sus causas y, por ende, se
enfocan casi exclusivamente en la asistencia primaria (Dinamia, 2020). Por lo tanto, a pesar de que en el Plan se reconocen diferentes manifestaciones de la VBG, esto no se traduce en medidas concretas. En este sentido, no hay una atención integral a menores de 18 años, aunque el SRI tiene mecanismos de coordinación con INAU a través de derivaciones. Las campañas mencionadas en el apartado previo, dirigidas a la juventud además de acciones de formación y sensibilización en entornos educativos tanto para estudiantes como para docentes, no componen una estrategia coordinada a nivel nacional, sino que son más bien acciones puntuales (Dinamia, 2020).

Como se analizará más adelante en este capítulo, no se cuenta con un sistema interinstitucional que permita dimensionar el alcance en conjunto de los servicios y programas, no obstante, es posible medir el alcance por separado de los diferentes componentes del SRI. En el período 2015-2018 ingresaron a los servicios de atención del Inmujeres 7.492 mujeres, aproximadamente 2.500 por año. En cuanto al servicio de trata, atendió a 464 mujeres en dicho período. Por otra parte, el programa Comuna Mujer de la IM atendió a 18.079 mujeres, aproximadamente 6.000 cada año. Mientras que los equipos de referencia del MSP atendieron a 1.317 mujeres en el año 2018^[No se dispone información para años anteriores.]. Respecto a la atención a niñas, niños y adolescentes, el SIPIAV alcanzó a 3.688 menores que vivieron situaciones de VBG. Por último, a través de la línea telefónica se orientó a 10.955 personas (Dinamia, 2020).

### Protección a las mujeres en situación de VBG, resocialización a varones y acceso a la justicia

El Inmujeres además de los servicios de atención a mujeres, como parte de su respuesta
integral, brinda servicios a varones que ejercen o han ejercido violencia basada en género y quieren dejar de hacerlo. El trabajo en paralelo con las mujeres y los varones agresores permite monitorear la situación y ajustar la intervención (Ruíz, Olsen y Eiris, 2018). Actualmente, existen 12 equipos que trabajan en 17 puntos del país. Un servicio similar, de resocialización a varones es dirigido por la IM.

En particular, el Inmujeres tiene a cargo de un equipo especializado para la atención a los varones que tienen colocada la tobillera. Justamente, en relación con el monitoreo de las situaciones de VBG, desde 2013 a cargo del MI, funciona el Programa de Tobilleras Electrónicas para verificar la localización del varón violento y supervisar el cumplimiento de las medidas de protección dispuestas por la justicia competente. Esta tecnología se utiliza en aquellas situaciones consideradas de alto riesgo, y supone un dispositivo colocado a la mujer en situación de VBG y otro a su agresor, estos se mantienen vinculados y permiten la localización permanente de ambas personas (Dinamia, 2020; Gularte et al., 2020). Actualmente, el Programa se extiende a todo el país, pero es persistente la denuncia de la sociedad civil acerca de la falta de dispositivos. De hecho, la sociedad civil integra la comisión interinstitucional de seguimiento del programa, junto con el Poder Judicial, la Bancada Bicameral Femenina, Inmujeres, INAU, Policía Nacional y, quien la lidera, la División Políticas de Género del MI (Gularte et al., 2020).

Para las mujeres y sus hijas/os que están en situaciones que suponen riesgo de vida y no
tienen un lugar seguro donde hospedarse, el Inmujeres brinda soluciones habitacionales
transitorias. Actualmente, existen 3 modalidades de alojamiento transitorio: una Casa de Breve Estadía (CBE) para riesgo inminente de vida, dos Centros de Estadía Transitoria (CET) para mujeres en riesgo moderado de vida (uno de estos se encuentra en Montevideo y el otro en Tacuarembó) y un Centro de Medio Camino (CMC) para mujeres que están en proceso de salida de situaciones de violencia doméstica (CNC, 2020). El dispositivo CBE brinda alojamiento y atención por un plazo de hasta 30 días, los centros están gestionados por ONGs y supervisados por el Inmujeres. La forma de ingreso a las soluciones habitacionales transitorias es a través del Portal del Inmujeres que funciona las 24 horas. Una vez ingresada una consulta el equipo derivante realiza un informe al Portal, donde se describe la situación y se fundamenta sobre el riesgo de vida que corre la mujer. El ingreso, a su vez, requiere de un compromiso por parte de la mujer de cumplir las reglas básicas de convivencia, su disposición a recibir asistencia y orientación psico-social y legal y a no mantener contacto con el agresor o personas allegadas a él mientras permanezca allí (Inmujeres, 2016).

En relación con el acceso a la justicia, el Poder Judicial cuenta con Juzgados Letrados de
Familia Especializados ubicados en Montevideo^[En Montevideo hay un total de 10 Juzgados Letrados de Familia Especializados de atención permanente, con doble turno durante todos los días del año.]. En el interior del país frente a situaciones de VBG, y mientras no se creen los Juzgados Letrados Especializados en Violencia Basada en Género, Doméstica y Sexual previstos en el Art. 51 de la Ley 19.580, les compete actuar a los Juzgados de Paz. Los Juzgados con competencia en materia de familia, también actúan en cuestiones no penales de VBG (CNC, 2020).

En cuanto al alcance de estos dispositivos de protección en el período 2015-2018 se observa que el Inmujeres atendió a 1.138 varones violentos, mientras que la IM hizo lo propio con 246 varones. Respecto a los dispositivos habitacionales, el Inmujeres brindó alojamiento en las Casa de Breve Estadía a 133 mujeres y 221 niñas, niños y adolescentes. Entre 2017 y 2018 se alojaron en Centro de Estadía Transitoria 31 mujeres y 50 menores. Mientras que en 2019 pasaron por las Centro de Medio Camino 6 mujeres y 16 menores (Inmujeres, 2019). Por otra parte, la FGN brindó atención a más de 2.000 víctimas y testigos, mientras que 253 personas fueron incluidas en el programa de medidas especiales de protección. El MI recibió 40.467 denuncias por violencia doméstica y delitos asociados. Mientras que el MSP en el periodo marzo-setiembre atendió a 2.441 mujeres por VD y 126 por violencia sexual fuera del ámbito doméstico en el sector privado (Dinamia, 2020).

Respecto a los servicios y dispositivos actuales de combate a situaciones de VBG, se
encuentran orientados fundamentalmente a cubrir las necesidades prácticas, es decir a cubrir una carencia inmediata vivida por esas mujeres en situación de VBG, tales como la vivienda para ellas y sus hijas/os, la formación o acceso al empleo y su atención psico-social. Los programas destinados a cubrir los intereses estratégicos tienen un alcance bastante acotado tanto en sus propósitos como por la cantidad de mujeres que incluye como se analizará en el siguiente apartado. A su vez, los servicios de resocialización de varones, solo están orientadas a varones agresores, dejando de lado el trabajo sobre las masculinidades en general (Dinamia, 2020).

### Programas de salida de la situación de VBG

El único dispositivo que brinda una solución habitacional es el Programa Alternativas
Habitacionales a cargo del Inmujeres en convenio con el Ministerio de Vivienda Ordenamiento Territorial y Medio Ambiente. Este programa surge en 2009 y tiene como población objetivo a las mujeres con o sin personas a cargo que transitan procesos de salida de situaciones de VBG. Para la efectivización de la solución habitacional se otorga una garantía de alquiler y un subsidio por un monto de 12 Unidades Reajustables durante un período de hasta dos años. Existen una serie de requisitos que estas mujeres deben cumplir para poder acceder al programa: estar asistiendo a un servicio especializado en VBG desde hace al menos 6 meses, estar transitando por un proceso de salida de la situación de violencia y tener un ingreso que le permita afrontar los gastos básicos de la vivienda. Además, en los casos en que los servicios de atención intervienen se requiere que evalúen si el componente habitacional es indispensable para la superación del problema (Inmujeres, 2016). En 2019, el Programa de Alternativas Habitacionales tuvo 454 mujeres activas, siendo 173 de ellas nuevos ingresos durante dicho año.

Otro componente clave en la salida que busca generar autonomía económica en las mujeres,
refiere al empleo. Inmujeres en convenio con el Instituto Nacional de Empleo y Formación
Profesional gestiona el Programa Alternativas Laborales que brinda cursos de capacitación para el empleo. Por otro lado, a través de un convenio marco entre el Inmujeres y la IM acceden a pasantías laborales mujeres en proceso de salida de situaciones de violencia (CNC, 2020).

Como se desprende de lo anterior, los programas de salida de las situaciones de VBG son
los menos desarrollados dentro del SRI. Si los dispositivos mencionados en el apartado anterior se vinculan a las necesidades prácticas, los descritos en este, se vinculan a los intereses estratégicos. El proceso de transformación social requiere trabajar en simultáneo con las necesidades prácticas y los intereses estratégicos (Braunmühl, 2001), por lo tanto, es necesario desarrollar mucho más las acciones que permitan a las mujeres alcanzar sus intereses estratégicos. Por ejemplo, el apoyo solamente práctico de las mujeres (otorgarle un lugar para alojarse temporalmente) sin el combate paralelo a las desigualdades de género (promover un cambio cultural y la autonomía de esas mujeres), pierde la esencia emancipadora del concepto de género. Y, por otro lado, la búsqueda de objetivos estratégicos sin contemplar las condiciones de vida y los intereses de las mujeres lo vuelve una ideología vacía. Dicho de otro modo, en las políticas públicas para enfrentar la VBG, no solo son imprescindibles las acciones de prevención y asistencia para atender las necesidades prácticas de las mujeres en situación de violencia, sino también, las acciones tendientes a cubrir sus intereses estratégicos que permitan modificar sustancialmente su situación.

### Sistemas de información

Las diferentes instituciones que componen el SRI cuentan con sistemas de información que les permiten realizar el monitoreo y evaluación de los diferentes programas y servicios. En los sistemas de información se registran las consultas, atenciones, derivaciones y denuncias de las situaciones de VBG que atraviesan las mujeres. En este apartado se desarrollan los sistemas de información del Inmujeres y el MI por ser dos de las instituciones más importantes dentro del SRI.

El Inmujeres cuenta desde 2008 con el SIG que se encarga del procesamiento y análisis
de información para evidenciar las desigualdades entre varones y mujeres. El SIG se alimenta de datos producidos por el Instituto Nacional de Estadística, Ministerio de Salud Pública, Oficina Nacional de Servicio Civil, Corte Electoral y Gobiernos Municipales. A su vez, trabaja con la información que releva el propio instituto sobre los diferentes componentes del Sistema de Respuesta.


A partir del Sistema de Monitoreo, Administración y Resolución de Trámites (SMART),
el SIG obtiene información estandarizada y sistemática sobre las intervenciones, y además,
obtiene otros datos por fuera de este sistema que son recopilados en planillas electrónicas y el software EPIDATA. De acuerdo a la persona responsable del SIG de Inmujeres, todas las intervenciones en los servicios se ingresan al SMART, sin embargo, los demás componentes del sistema de respuesta del Inmujeres (programas habitacionales, etc.) ingresan la información en EPIDATA y los servicios de trata lo hacen en planillas electrónicas. El SMART no se conecta ni alimenta de las planillas ni del EPIDATA, por lo tanto, la información queda fragmentada según el tipo de servicio o programa que sea la fuente. En el SMART se recoge un conjunto de datos horizontales, comunes a todos los servicios y programas del MIDES (datos filiatorios, educación, situación laboral, situación de discapacidad, entre otros) y un módulo específico para completar cuando se realiza una intervención por una situación de VBG. En este módulo se detallan los factores de riesgo^[Los factores de riesgo considerados se detallan en el Anexo.] y, eventualmente, si el agresor tiene colocada la tobillera se despliega otro
módulo específico.

Por su parte, el MI desde 2013 cuenta a nivel nacional con el SGSP, donde se registran
las denuncias en general, y cuenta con un módulo específico para las denuncias por VD. Este módulo permite vincular otros delitos asociados a la VD, por ejemplo, lesiones, amenazas, violencia privada, suicidios, homicidios, etc. (Gularte et al., 2020). La ficha de VD incluye variables básicas sobre el hecho y la persona denunciante: fecha de ingreso, fecha del hecho, lugar, departamento, edad de la víctima, vínculo con el agresor, cantidad de hijas/os, tipo de violencia, entre otras. Este sistema interopera en tiempo real con el sistema informático del Programa de Tobilleras del propio MI y también con el Sistema de Información del Proceso Penal Acusatorio de Uruguay (SIPPAU) de la FGN. Este último, es el único ejemplo de interoperabilidad entre dos instituciones del SRI (CNC, 2020).

No existe ningún tipo de interoperabilidad entre el SIG y el SGSP y, por ende, no hay un
sistema unificado ni un conjunto común de variables relevadas por cada sistema que de cuenta de todos los componentes del SRI. Dado que cada institución reporta datos por separado y no existe un sistema informático unificado, no se puede determinar la cantidad de mujeres que son atendidas o consultaron por situaciones de VBG en el SRI. Del mismo modo no se puede seguir una trayectoria de esas mujeres en las diferentes instituciones del Estado, ni hacer derivaciones oportunas. Las personas entrevistadas del Inmujeres y el MI, consultadas sobre la necesidad de lograr un sistema interoperable que permita conocer la trayectoria de las mujeres en el SRI y abordar a tiempo las situaciones, coincidieron en la importancia de contar con un sistema de esas características:

    > Se acaba de hacer un diagnóstico de qué releva cada organismo [aún no es público]...Está bastante consensuado, en la gestión anterior y en esta, que esas cosas [un sistema interoperable] son necesarias [...] Ahora desde el Observatorio [OVBG], estamos intentando dejar como un proyecto de trabajo justamente para lograr homogeneizar variables. Ya hay un avance también en el marco del Consejo [CNG] y así poder en algún momento plantearnos por lo menos un mínimo de interoperabilidad entre las  instituciones para intercambio de información y para tener como una visión de la trayectoria de esa mujer, evitando la revictimización (Responsable del Sistema de Información de Género Planificación, Gestión y Desarrollo, Inmujeres-MIDES).
    Creo que lo que falta es eso, que todas las instituciones tengamos un lugar en común donde volcar esa información, que todas podamos acceder. Es uno de los cometidos del Observatorio. Ahora lo venimos haciendo entre el Inmujeres y el MI porque así se fue dando y así surgió y se armó ese convenio. El marco institucional debería ser el Observatorio (Responsable del Departamento de Generación de Conocimiento y Orientación Metodológica, Inmujeres-MIDES).
    
Además, consideran que se necesita voluntad política y presupuesto para concretar el
desarrollo de un sistema interoperable, como se evidencia en esta cita:

    > Se necesita voluntad política porque son organismos compartiendo información, y eso nunca es fácil. Se necesita desarrollos informáticos y se necesita ajustar bien los protocolos. El acceso a esta información es sensible [...] También está la posibilidad de hacer una especie de SIIAS [Sistema de Información Integrada del Área Social], juntar bases cada seis meses y poder tener una base de datos de todas las mujeres que consultaron en todos los servicios del Estado, donde estuvo cada una, para poder identificar algunos recorridos. Eso sería avanzar para otro lado, gestión de la información para evaluar políticas (Responsable del Sistema de Información de Género Planificación, Gestión y Desarrollo, Inmujeres-MIDES).
    
    
De acuerdo a estas apreciaciones y al estado actual de desarrollo de los sistemas de
información, no parece que ocurra en el corto plazo la creación de un sistema interinstitucional.  Además, las personas entrevistadas coinciden en que primero es necesario mejorar los registros de cada institución antes de ponerlos en común, lo que requiere un trabajo a la interna de cada organismo. Antes de avanzar en un sistema interinstitucional es necesario mejorar el relevamiento de las respectivas fichas para atender situaciones de VBG. El MI ha trabajado en la capacitación para completar la ficha de VD en los casos que corresponda, pero aún así es evidente que se necesita mejorar la calidad de la información que allí se carga. 

    > Dentro del Observatorio [OVBG] una de las cosas que apuntamos es dentro de algún tiempo, tener una base única [...] Cuando trabajamos en la rendición de datos que se hace cada 25 de noviembre, tenemos que hacer una muestra representativa, porque la información está en la narración de esa denuncia (Integrante del Área de Análisis Criminal y Estadístico en VBG, División Políticas de Género – MI).
    
Respecto al registro de femicidios, el MI lleva una base de datos sistematizada de los
homicidios a mujeres desde 2012 a la actualidad^[Estos datos anonimizados están publicados como datos abiertos solo para el año 2018.]. Esta base consume información del SGSP, pero se complementa con variables que deben ser sistematizadas a partir de la lectura de los partes policiales. Recientemente, a partir de la investigación de Gularte et al. (2020), la base fue mejorada y trabajada en conjunto entre la División de Políticas de Género del MI y el Inmujeres. A partir de estos datos se puede saber que solo una cuarta parte de estas mujeres víctimas de femicidio hizo una denuncia previa. Según la persona referente de la División Políticas de Género del MI, “la mayoría de los femicidios no tienen denuncia previa por lo que sabemos mucho sobre el hecho, pero no sabemos la trayectoria” (Área de Análisis Criminal y Estadístico
en VBG, División Políticas de Género – MI).

Respecto al registro de víctimas de femicidio es importante evidenciar que ni los sistemas
de información, ni los informes del Inmujeres dan cuenta de la cantidad exacta de mujeres
víctimas de femicidio que se atendieron alguna vez o consultaron en un servicio del Inmujeres. La información que le proporciona el MI al Inmujeres luego de un femicidio, se utiliza para chequear si esa mujer había estado en contacto con algún servicio, pero este dato no se publica. 

Como afirmó la persona Responsable del Departamento de Generación de Conocimiento
y Orientación Metodológica del Inmujeres: “en base a los datos, las mujeres que han asesinado que participaban de algunos de nuestros servicios son muy pocas”. Este dato es muy relevante y tiene una doble lectura, por un lado, podría estar indicando que los servicios trabajan bien en detectar el riesgo de vida y con sus acciones logran evitar un feminicidio. Por otro lado, deja en evidencia la ausencia del Estado para detectar y proteger a las mujeres que resultan víctimas de feminicidio. En casos de que estas situaciones hubieran sido detectadas por otros organismos del Estado (ANEP, ASSE y las instituciones privadas de salud) no existieron derivaciones oportunas. Como muestran las investigaciones sobre feminicidios en Uruguay y se verá en el siguiente capítulo, la mayoría de éstos son cometidos por la pareja o ex-pareja de la mujer asesinada. Por
lo tanto, no son hechos puntuales, sino que se dan en el marco de una situación de VBG
estructural que el Estado no pudo detectar o no intervino adecuadamente.

Esto deriva directamente en la pregunta ¿a quiénes llegan los servicios del SRI, y del
Inmujeres en particular?, O mejor dicho, ¿quiénes llegan a estos servicios y dispositivos? En teoría, aunque no se explicita en ningún documento oficial, la población objetivo del SRI debiera ser, al menos, unas 170.000 mujeres uruguayas (23,7%) que declararon haber vivido violencia en su relación de pareja en el último año, según se desprende de la segunda encuesta de EVBGG (Observatorio de Violencia Basada en Género, 2019). Esta cifra está lejos de ser alcanzada aún tomando todos los componentes del SRI. En el período 2015-2018, se realizaron casi 40.000 intervenciones entre los diferentes programas y servicios del SRI con un promedio anual de 13.000 intervenciones aproximadamente. La falta de un registro unificado sobre las distintas acciones, servicios y programas dificulta el cálculo de la población beneficiaria, pero suponiendo que cada intervención corresponde a una persona, la cobertura^[La cobertura se calcula como el cociente entre cantidad de beneficiarias y la población objetivo, multiplicado por 100.] anual es aproximadamente de un 8%.

En la evaluación del Plan de Acción 2016-2019 realizada por Dinamia (2020), se concluye que es necesario un compromiso político firme que se materialice en una asignación relevante de recursos financieros y humanos para abordar la problemática de la VBG como un
“problema de Estado”. En este sentido, a nivel de desempeño y cobertura, se sugiere continuar avanzando en fortalecer la asignación de recursos para reforzar el sistema de atención y respuesta a mujeres en situación de VBG, de manera de ampliar el número de servicios y plazas disponibles de recursos habitacionales. A su vez, se sugiere realizar un diagnóstico específico de los diferentes programas habitacionales que permita estimar su cobertura a partir de la definición de la población potencial y objetivo. Se recomienda reforzar y/o crear recursos específicos habitacionales, de salud, formación e inserción laboral para las mujeres víctimas de trata. Por último, a nivel de las Comisiones Departamentales se considera clave, la asignación de recursos humanos y financieros específicos, que permitan la permanencia de los equipos en el territorio (Dinamia, 2020).

Acerca del SRI de acuerdo a lo que se desprende de la evaluación de Dinamia (2020) y lo
analizado en este capítulo, se puede concluir que hay déficits en el sistema de prevención, detección y protección que se traducen en un alto número de femicidios. A su vez, el abordaje institucional de intervención se encuentra fragmentado por lo territorial (Montevideo/interior, y capitales departamentales/localidades y zonas aisladas). Por último, el registro y medición de la violencia basada en género es fragmentada, al no haber un sistema integrado de información a nivel nacional.

