# Consideraciones finales

Esta investigación abordó el tema de los feminicidios ocurridos en Uruguay entre 2001 y 2019. Para dar cumplimiento al objetivo general propuesto, generar herramientas que aporten a una mayor comprensión del fenómeno del feminicidio, se procesó la base de datos de feminicidios para estandarizar los registros y construir nuevas variables con el propósito de realizar un análisis cuantitativo.

El análisis descriptivo arrojó que durante el período analizado 2001-2019, el fenómeno se mantuvo relativamente estable entorno a una tasa de 1,7 feminicidios cada 100.000 mujeres con una mayor incidencia en mujeres jóvenes y en edad reproductiva, donde la tasa se ubica entorno a 2,4.

La mayoría de los feminicidios fueron cometidos por la pareja, la ex-pareja (81%) o un familiar de la mujer asesinada (11%) y gran parte de estos ocurrieron en su vivienda (64,4%). Si se consideran solamente los feminicidios perpetrados por la pareja o ex-pareja de la mujer asesinada, en el 38% de los casos, el feminicida se suicidio o intentó suicidarse luego de cometer el crimen. Esta característica es un patrón bastante frecuente en este tipo de feminicidios y como se analizó en el Capítulo 1, se denominan suicidios machistas. Se producen cuando la mujer quiere terminar la relación de pareja o ésta ya terminó, y el feminicidio es una forma de no aceptación de esta situación dado que la mujer-objeto de su propiedad no puede dejar de pertenecerle. Pero al mismo tiempo una vez que se produce el feminicidio ese varón ya no tiene razones para vivir y se suicida.

Los feminicidios no ocurren como hechos aislados, sino que se enmarcan en la violencia
estructural que viven las mujeres basada en género. En particular, la mayoría se dan en el marco de una relación de pareja y, por ende, existe una situación previa de VBG. Se constató que en muy pocos casos estas mujeres habían recurrido a servicios de atención del Inmujeres y según datos del MI, apenas 1 de cada 5 había realizado una denuncia policial contra su agresor. En parte, esto podría explicarse por varios motivos: que la mujer no visualice que corre riesgo su vida, que se encuentre en un estado de sujeción y/o aislamiento que tenga miedo, vergüenza o cualquier otro sentimiento que le impida pedir
ayuda a su entorno o a los servicios estatales disponibles. El no recurrir a los servicios se puede deber a que no los conoce, no le brindan seguridad, o que no cuenta con los recursos para hacerlo, pero en definitiva, no encuentra en estas opciones una solución a su problema.

Respecto a la hipótesis que guió la investigación, es decir, que la situación de vulnerabilidad socioeconómica o falta de autonomía económica de las mujeres las expone en mayor medida a sufrir un feminicidio, para Montevideo se encontró cierta evidencia a su favor. En particular, el análisis espacial para Montevideo ha proporcionado pruebas empíricas de la concentración de un grupo de CCZs de centro-oeste con altas tasas de feminicidios y otro grupo de CCZs al sur del departamento con bajas tasas de feminicidios. Dado que la zona centro-oeste presenta niveles más altos de incidencia de la pobreza y la zona sur es la región de Montevideo con niveles más bajos de incidencia de la pobreza, este resultado es una evidencia a favor de la hipótesis de la investigación. A su vez, el análisis estadístico a partir de los modelos de regresión arrojó la existencia de una relación positiva entre la incidencia de la pobreza y la tasa de feminicidio. Sin embargo, estos resultados se constataron considerando todos los datos, no así cuando se utilizaron únicamente los datos de los feminicidios ocurridos en la vivienda. Por lo tanto, solo parcialmente se puede considerar una evidencia en favor de la hipótesis planteada. Es necesario seguir profundizando en el análisis para confirmar la robustez de los resultados a lo largo del tiempo.

Por otro lado, para el interior del país se constató que los feminicidios se concentran en
departamentos del noreste del país (Treinta y Tres, Cerro Largo, Rivera) y Flores donde se registran las tasas más altas, en todos los casos superiores a 2 feminicidios cada 100.000 mujeres. Al desagregar esta información según el tamaño de la localidad en la que se produjeron, la evidencia muestra una mayor tasa de feminicidio en las localidades pequeñas y en la zona rural. Estas localidades en general no presentan servicios de atención del Inmujeres, de hecho, de los 33 servicios solo 2 se encuentran en localidades de menos de 5.000 habitantes. Lamentablemente la calidad de los datos no permitió realizar el mismo análisis estadístico que para Montevideo, lo que imposibilitó poner a prueba la hipótesis y
responder para esta parte del país algunas preguntas de investigación.

Otro de los objetivos de la investigación fue el análisis de la política pública vigente de combate a la VBG. A partir de la revisión de documentos institucionales, de las principales leyes, y la realización de entrevistas a informantes calificadas/os se lograron mapear los principales componentes de la política pública. No obstante, pese al rol activo que ha tenido el Estado, plasmado en el Plan de Acción 2016-2019 y la promulgación de leyes (VBG, femicidio y trata de personas), no se modificó sustantivamente ni la cantidad de mujeres que declaran vivir situaciones de VBG (de acuerdo a las EVBGG), ni la cantidad de feminicidios que ocurren anualmente.

En este sentido, la promulgación de la ley de femicidio como agravante no muestra un impacto en la cantidad de femicidios ocurridos, aunque únicamente se pueden analizar dos años desde que entró en vigencia. No obstante, la ley es importante para evidenciar el problema, tal como el movimiento feminista organizado preveía, no desestimula los femicidios, ya que no ataca sus causas. De hecho, una parte importante de los feminicidas se suicidan luego de cometer el crimen por lo que no se puede sentenciar al agresor.

Respecto a la política pública analizada, se constata una serie de limitaciones o fallas. No está claramente definida ni cuantificada la población objetivo y, por ende, no se pueden definir los “cupos” que debería tener cada servicio o programa. Asimismo, no se cuenta con un sistema de información estandarizado que nuclee la información de las diferentes instituciones que integran el SRI. La carencia de un sistema de información de este tipo impide estimar la cobertura de los dispositivos y servicios. A su vez, no permite seguir la trayectoria de las mujeres dentro del sistema, lo que permitiría obtener alertas y hacer derivaciones oportunas entre instituciones. Tampoco incorporan el registro de variables
imprescindibles para conocer sus condiciones de vida y grados de autonomía económica u otros recursos con los que cuentan tales como, nivel educativo, trabajo remunerado (y sus condiciones laborales), si cuentan con otros ingresos, si tienen vivienda propia, etc.

Para las mujeres víctimas de feminicidio no hay información sistematizada que permita saber si habían consultado en algún servicio del SRI. Solo está sistematizado si realizó alguna denuncia por VD. A partir de las entrevistas se pudo relevar que es relativamente bajo el número de mujeres atendidas por el Inmujeres que fueron víctimas de feminicidio. Este dato podría estar indicando que los servicios trabajan bien en detectar el riesgo de vida y que con sus acciones logran evitar un feminicidio. Por otro lado, deja en evidencia la ausencia del Estado para detectar y proteger a las mujeres que resultan víctimas de feminicidio. En casos de que estas situaciones hubieran sido detectadas por otros organismos del Estado (ANEP, ASSE y las instituciones privadas de salud) no existieron derivaciones oportunas.

Respecto a los programas y servicios brindados, el Inmujeres concentra gran parte de estos.
Esto muestra que la política pública de combate a la VBG no ha calado hondo en otras instituciones del Estado que debieran ofrecer su propio abordaje, me refiero a la ANEP y el SNIS fundamentalmente. Por ejemplo, las acciones de sensibilización no permean el núcleo duro del sistema educativo y tampoco tienen una amplia cobertura de los medios masivos de comunicación.

Por otro lado, para las mujeres que si son atendidas por los servicios del Inmujeres las
soluciones a sus necesidades prácticas e intereses estratégicos resultan insuficientes. En particular, es pequeño el cupo de soluciones para la salida de las situaciones de VBG en materia de alojamiento y empleo. La respuesta de atención habitacional atiende solamente a mujeres en situación de VBG que está en riesgo su vida, mientras que las soluciones de más largo plazo, son sumamente reducidas.

En teoría, aunque no se explicita en ningún documento oficial, la población objetivo de la red de respuesta debiera ser unas 170.000 mujeres uruguayas, según se desprende de la segunda encuesta de EVBGG. Esta cifra está lejos de ser alcanzada aún tomando todos los componentes del SRI. En el período 2015-2018, se realizaron casi 40.000 intervenciones entre los diferentes programas y servicios del SRI con un promedio anual de 13.000 intervenciones aproximadamente. La falta de un registro unificado sobre las distintas acciones, servicios y programas dificulta el cálculo de la población beneficiaria, pero suponiendo que cada intervención corresponde a una persona^[Este supuesto es necesario ya que no es posible conocer el dato de cantidad de mujeres que consultaron, solamente la
cantidad de consultas que se realizaron.], la cobertura anual es aproximadamente de un 8%. Por lo tanto, aún asumiendo el supuesto más laxo, se obtiene una cobertura muy baja.

Dentro de los factores de riesgo que se analizan para atender las situaciones de VBG que se
presentan en los diferentes servicios se consideran: la falta de autonomía económica, la pobreza y pobreza extrema, la pérdida de empleo o carencia de ingresos propios, a su vez, también se toman en cuenta la asimetría en la relación, por ejemplo, por edad o autonomía económica. Esto muestra que el Estado maneja una visión interseccional de la problemática. Sin embargo, la mayoría de los feminicidas no habían tenido una denuncia previa y, por otro lado, la mayoría de las mujeres asesinadas no había recurrido nunca a los servicios del Inmujeres. Es posible que estas mujeres no hayan visualizado que corría riesgo su vida y por eso no recurrieron a los servicios ni denunciaron. También esto muestra que el Estado no llegó a atender las situaciones de estas mujeres. Como ya fue discutido, si la mayoría de los feminicidios perpetrados por la pareja o ex-pareja se producen luego de la ruptura de la relación o cuando la mujer manifestó su intención de separarse, y el Estado está ausente, las condiciones materiales para poder efectuar de forma segura esa separación son importantes. En este sentido, es relevante sistematizar esta información oportuna y adecuadamente para ajustar los dispositivos y servicios ofrecidos.

Los servicios, programas y dispositivos están centrados en las situaciones de VBG en las
relaciones de pareja. Si bien hay justificación para que la política se concentre en atender situaciones de VBG que se originan en una relación de pareja, es necesario, abordar más enfáticamente el problema desde sus orígenes, desde la educación en la infancia y adolescencia con énfasis en los noviazgos libres de violencia y las violencias que viven las mujeres en todo ámbito. Es necesario un cambio cultural que cuestione la masculinidad hegemónica y los estereotipos de género.

En resumen, se espera que el análisis estadístico realizado de los feminicidios ocurridos en Uruguay en las últimas dos décadas, en conjunto con el análisis de la política pública de combate a la VBG, constituyan un aporte, tanto para los estudios académicos especializados, como para la elaboración y diseño de políticas específicas.

