# Aproximación teórica


Durante el desarrollo de esta investigación se consideran una serie de categorías de
análisis que sitúan el problema estudiado. Primero se introduce la idea de violencia como
disciplinamiento de las mujeres en el sistema patriarcal-(pre)capitalista, a partir de la caza de brujas de los siglos XV a XVII (Chollet, 2019). Con el advenimiento del capitalismo, las mujeres son devaluadas socialmente y mandatadas a asumir el rol, la responsabilidad y las tareas vinculadas a la actividad reproductiva en el ámbito privado o doméstico (limpieza, mantenimiento de los hogares y cuidado de sus integrantes) de forma no remunerada y los varones a adoptar el rol de proveedores de ingresos trabajando de forma remunerada fuera del ámbito doméstico (Mies 2019, Federici 2010). Esto está ligado a la división sexual del trabajo que no sólo pauta roles y comportamientos diferenciados entre los géneros, sino que implica una desigual valoración social de éstos, dejando en posiciones más desfavorables y desventajosas a las mujeres respecto a los varones. Si bien a lo largo del tiempo se producen cambios en la inserción de las mujeres en el mercado de trabajo, la división sexual del trabajo sigue operando al día de hoy.

Luego se introduce el concepto de género, violencia basada en género e interseccionalidad como una herramienta metodológica conceptual para abordar la violencia ejercida sobre las mujeres por su condición femenina. Para comprender la violencia hacia las mujeres, es indispensable analizar las percepciones y valoraciones que existen en cierta cultura
sobre lo que significa ser varón y ser mujer. En este sistema patriarcal-capitalista, prevalece la idea de la superioridad del varón respecto a la mujer y se reproducen prácticas íntimas y públicas que operan con base en este esquema. En particular, en las relaciones de pareja esta idea de superioridad alimenta la creencia de que el hombre tiene el derecho a utilizar su autoridad y/o su fuerza para mantener el dominio y control sobre la mujer.

Finalmente se plantean los conceptos de femicidio y feminicidio que representan una de
las violencias más extremas basada en género que termina con la vida de mujeres. Se analizarán estos conceptos a partir de las similitudes y diferencias. En esta investigación se utiliza el término feminicidio propuesto por Lagarde (2008), ya que implica el reconocimiento del papel del Estado como garante de la vida de sus ciudadanas y ciudadanos. En este sentido, un feminicidio no es un asunto privado que atañe al asesino y su víctima, sino que hay una responsabilidad estatal.

## La violencia como disciplinamiento de las mujeres {.unnumbered}

El término femicidio es relativamente reciente, se comienza a usar en los años 90, sin
embargo, Chollet (2019) sostiene que el femicidio siempre estuvo presente como una práctica
para dominar completamente a las mujeres, es decir, ha servido como una política de
dominación. La autora se remonta a la caza de brujas que tuvo lugar en Europa y América entre los siglos XV a XVII y supuso la persecución, tortura y asesinato de miles de mujeres, en su mayor parte pobres, a manos de la iglesia católica y el Estado (Chollet, 2019; Mies, 2019).

La independencia sexual y económica que tenían las mujeres en la época feudal, las
campesinas y artesanas, suponía un peligro para la emergente burguesía por lo que era necesario controlarlas y subordinarlas (Mies, 2019). La caza de brujas fue un proceso fundante del capitalismo a partir de la sumisión de las mujeres a los hombres. Federici (2010), Chollet (2019) y Mies (2019) concluyen que la caza de brujas, junto al colonialismo, la esclavitud y la explotación de los recursos naturales, fue un hecho clave para la consolidación del capitalismo y simultáneamente de la opresión de las mujeres. Es justamente en esta época de transición del feudalismo al capitalismo y durante el proceso de acumulación capitalista, que se produce un disciplinamiento y devaluación del trabajo de tipo reproductivo (cuidados y mantenimiento de los hogares) tradicionalmente asignado o ligado a las mujeres (Federici, 2010). Este disciplinamiento brinda a los hombres el control sobre los cuerpos de las mujeres y los autoriza a ejercer violencia psicológica, física y sexual sobre éstas. Federici (2010) retoma de Carol Pateman su teoría del contrato sexual para explicar la división sexual del trabajo como sustento de la economía capitalista:


> Fue a partir de esta alianza entre los artesanos y las autoridades de las ciudades, junto con la continua privatización de la tierra, como se forjó una nueva división sexual del trabajo o, mejor dicho, un nuevo ‘contrato sexual’, siguiendo a Carol Pateman (1988), que definía a las mujeres -madres, esposas, hijas, viudas- en términos que ocultaban su condición de trabajadoras, mientras que daba a los hombres libre acceso a los cuerpos de las mujeres, a su trabajo y a los cuerpos y el trabajo de sus hijos (Federici, 2010, p. 147).

Federici y Mies plantean cómo con el advenimiento del capitalismo se constituye un
nuevo orden patriarcal, en el que a las mujeres primero les fue arrebatada la propiedad de la tierra y luego, a partir de la segunda mitad del siglo XIX, éstas fueron expulsadas del trabajo asalariado y confinadas al interior del hogar. Así se conforma la familia nuclear cuyo ingreso es el salario masculino que permite al capital tener un trabajador más productivo^[El pasaje de la industria ligera a la industria pesada necesitaba un tipo de obrero más productivo y que viva más años. En el marco de movimientos sociales y políticos de la primera mitad del siglo XIX es que se produce una duplicación del salario al mismo tiempo que se rechazan a las mujeres en las fábricas para propiciar el desarrollo de
la nueva industria y asegurar la reproducción de la mano de obra (Federici, 2018).] y pacífico porque aunque sigue siendo explotado tiene una sirvienta en su casa (Federici, 2018). Esta división sexual del trabajo se basa en una relación asimétrica, jerárquica y explotadora, no es un simple reparto de tareas entre dos partes en igualdad de condiciones (Mies, 2019). 

En paralelo, junto a la división sexual del trabajo que confina a las mujeres al trabajo no remunerado en el ámbito privado, se impone el matrimonio como un objetivo para las mujeres.
Federici (2010) plantea que la forma de familia, tal cual la concebimos hoy, se gesta en el
capitalismo con la expulsión de las mujeres del trabajo asalariado en las fábricas y el
confinamiento en el hogar para producir y reproducir a la fuerza de trabajo. La asignación de un salario al obrero sin pagar la jornada de trabajo doméstico es la base de las desigualdades entre varones y mujeres al interior de las familias, y crea relaciones de poder, dominación y violencia sobre las mujeres. Así aparece la figura del ama de casa a tiempo completo. Al mismo tiempo que se produce la subordinación de la sexualidad de las mujeres a la reproducción de la fuerza de trabajo se impone la heterosexualidad como único comportamiento sexual aceptable (Federici,2018).

> Esta política, que hacía imposible que las mujeres tuvieran dinero propio, creó las condiciones materiales para su sujeción a los hombres y para la apropiación de su trabajo
por parte de los trabajadores varones (Federici, 2010, p. 149).


Federici (2010) resalta que en la transición entre el feudalismo al capitalismo con la
nueva división sexual del trabajo, se produjeron cambios culturales que reconfiguraron las
relaciones entre varones y mujeres a partir una sistemática campaña de degradación de las
mujeres y erosión de sus derechos. Se construyeron nuevos cánones culturales que establecieron que las mujeres eran naturalmente inferiores a los hombres y, por ende, debían estar bajo el control masculino. Las mujeres fueron sometidas a un proceso de degradación social que junto a la caza de brujas destruyó todo el acervo de conocimiento que ostentaban esas mujeres, sus prácticas y las formas de relacionamiento colectivo que había sustentado el poder que llegaron a tener en la Europa pre-capitalista. En el capitalismo, hacia fines del siglo XVII, surge un nuevo modelo de feminidad que confina a la mujer al hogar y a su rol de esposa pasiva, obediente y silenciosa (Federici, 2010).

Si bien a lo largo de la evolución del capitalismo algunas de estas características fueron
cambiando, por ejemplo, en algunos momentos las mujeres fueron masivamente reclutadas en las fábricas y, en otros, confinadas nuevamente al hogar, al día de hoy sigue operando la división sexual del trabajo. En el mercado laboral las mujeres se concentran en los empleos
pertenecientes al sector servicios relacionados directamente con las tareas reproductivas
(Federici, 2018). Mientras que en los hogares continúan siendo las responsables de las tareas de cuidados y mantenimiento no remuneradas, por lo que presentan una “doble jornada laboral” (Balbo, 1978).

El matrimonio y el papel de mujer-madre y ama de casa se consolida en el capitalismo
como parte central de la vida de las mujeres, incluso para aquellas mujeres que tienen un trabajo remunerado. Esto limita la autonomía económica que pueden tener las mujeres, a la vez, que impone ciertos mandatos culturales que operan en la subjetividad de éstas y, por ende, limitan su campo de acción. El cambio cultural que produjo un nuevo modelo de feminidad y masculinidad en mayor o menor medida sigue presente hasta la actualidad. Por lo tanto, estas categorías de análisis y este devenir histórico, son claves para entender la violencia que viven las mujeres basada en género.

## Género y Violencia basada en género {-}

El concepto de género surge en los años 60 en el ámbito de la psicología para explicar los
comportamientos e identidades de las personas más allá de su sexo biológico. En la década del 70 es apropiado y resignificado por las teóricas feministas estadounidenses para convertirlo en una categoría política. En la siguiente década surgen los “Estudios de género”, a partir de los cuales se comienza a cuestionar el determinismo biológico que imponía la subordinación de las mujeres por los hombres de manera natural y así se justificaban las desigualdades existentes (De Barbieri, 1997). En este sentido, estas autoras procuran diferenciar sexo de género, considerando al segundo un producto cultural a partir de la lectura del sexo biológico. Consideran que el sexo biológico está dado por la asignación dicotómica según la anatomía del cuerpo en cuestión, mientras que el género es una construcción socio-cultural de lo que significa ser hombre y ser mujer a partir de las diferencias sexuales y que sustenta el dominio de los hombres sobre las mujeres. En este punto vale destacar los aportes de las teóricas Gayle Rubin y Joan Scott. Rubin incorpora la noción de “sistema sexo-género” y lo define como el sistema de relaciones sociales
que transforma la sexualidad biológica en productos de actividad humana y que devienen en
necesidades sexuales históricamente específicas (De Barbieri, 1997). Mientras que Scott (1990) plantea que el género no es sólo un atributo de las personas -como se proponía desde la psicología- sino una construcción social y de cómo se construyen las relaciones de poder que se establecen entre hombres y mujeres. Por su parte, De Lauretis (1990) considera que un sistema de género se constituye por las concepciones culturales de lo masculino y lo femenino definidas como dos categorías complementarias aunque mutuamente excluyentes en las que los seres humanos están ubicados. Éste, es un sistema simbólico que asigna al sexo contenidos culturales de acuerdo con valores sociales y jerarquías.

A partir de la década de los noventa, influenciadas por ideas postestructuralistas, en
particular, de Michel Foucault, algunas autoras comienzan a cuestionar el binarismo del sexo y su determinismo biológico. Una de las mayores exponentes es Judith Butler (1990, 1993), quien en su obra busca demostrar que no solamente el género es una construcción cultural, sino también el sexo. En este sentido, Butler (1999) expone que al concebirse el sexo como algo natural, se reproduce el dualismo sexo-género. Sin embargo, argumenta que el género no necesariamente está determinado por el sexo, en el sentido que persona que nace hembra/macho no necesariamente tendrá una identidad de género mujer/hombre. Butler a lo largo de su obra plantea que el género es un acto performativo, ya que es a través de la reiteración de prácticas discursivas de sexo/género, materializada en cuerpos e identidades, que se reproduce la norma heterosexual. Para De Lauretis (1990), el género es una representación que tiene carácter político y que produce subjetividades. 

> El sistema sexo-género, en suma, es tanto una construcción sociocultural como un
aparato semiótico, un sistema de representación que asigna significado (identidad, valor,
prestigio, ubicación en la jerarquía social, etc.) a los individuos en la sociedad. Si las
representaciones de género son posiciones sociales que conllevan diferentes
significados, entonces, para alguien ser representado y representarse como varón o
mujer implica asumir la totalidad de los efectos de esos significados. [...] La
construcción del género es tanto el producto como el proceso de su representación (De
Lauretis, 1990, p. 11).

Para comprender la violencia hacia las mujeres, es indispensable analizar las
percepciones y valoraciones que existen en cierta cultura sobre lo que significa ser varón y ser mujer. En este sistema patriarcal-capitalista, prevalece la idea de la superioridad del varón respecto a la mujer y se reproducen prácticas íntimas y públicas que buscan reafirmar el cumplimiento de la norma. En las relaciones de pareja esta idea de superioridad alimenta la creencia de que el hombre tiene el derecho a utilizar su autoridad y/o su fuerza para mantener el dominio y control sobre la mujer.

La VBG se sustenta en una desigual distribución de poder, una desigual valoración de los
géneros, que habilita a la opresión de las mujeres por parte de los varones y las relaciones se vuelven asimétricas, reproduciéndose la supremacía de lo masculino. La violencia contra las mujeres basada en género es un componente estructural de un sistema que coloca a las mujeres en un nivel inferior y que las oprime de múltiples formas. Tal como lo sostiene la Red Uruguaya Contra la Violencia Doméstica y Sexual (2012, pp.15-16): “No se trata de una forma de violencia individual en función de la superioridad física, sino de relaciones de discriminación emergentes de la estructura social patriarcal”. Aunque las leyes ya no legitimen la violencia contra las mujeres, existen variados mecanismos por la que sigue ocurriendo.

> En la construcción de las identidades femeninas y masculinas, se depositan los
mandatos sociales/familiares sobre lo que se espera de un varón o una mujer. Los
varones también incorporan estas expectativas sobre sí mismos y puede llegar a sentirse
fracasado al no cumplirlas y en algunos casos emplear la violencia como forma de
descarga de esta frustración contra sí mismo o contra otros sobre los que tiene algún
poder, especialmente aquellas personas más cercanas a su entorno (Rostagnol, 2009, p.
33).

Los estereotipos de género favorecen el establecimiento de relaciones de dependencia por
parte de las mujeres, con base en los roles aprendidos durante el proceso de socialización
(Inmujeres, s.d.). Por ejemplo, una de las manifestaciones más significativas de la VBG es la violencia en las relaciones de pareja que muchas veces aparece tempranamente en el noviazgo. La violencia en el noviazgo implica una relación de poder y control que en general es más sutil y evoluciona de manera más lenta que la violencia basada en género en las relaciones de pareja adulta. En general, se da en una etapa de desarrollo de las mujeres que va pautando formas de relacionarse que luego tienden a repetirse en la vida adulta.

Incluso en esta etapa del noviazgo pueden formarse parejas abusivas. Vale la pena señalar
que algunas autoras se refieren a las denominadas parejas abusivas como aquellas en que una persona menor de edad establece un vínculo sexo afectivo con alguien 10 o más años mayor, lo que resulta en una diferencia de edad significativa sobre todo porque una de las personas aún está en pleno desarrollo (físico y psíquico) y la otra ya es adulta. Tal como expresa Tuana (2017, p.41): “en una pareja entre una adolescente y una persona adulta con más de diez años de diferencia no es posible garantizar un vínculo basado en la libre elección y en el consentimiento mutuo”. Son relaciones asimétricas marcadas por la diferencia de edad, de maduración y desarrollo cognitivo, de experiencias de vida y de autonomía física y económica. Las condiciones de vulnerabilidad económica suelen ser propicias para que se gesten este tipo de relaciones abusivas. La autora sostiene que cuando este tipo de relaciones se dan en contextos de pobreza extrema se refuerza la asimetría de poder y representa un abuso de la condición de vulnerabilidad de la adolescente, quien encuentra en esa relación, una especie de salida de su condición de vulnerabilidad. La evidencia muestra que la mayoría de las situaciones de VBG en la pareja comienzan en el noviazgo y luego se profundizan en la convivencia (Tuana, 2017). Por lo tanto, es relevante poner en evidencia que la VBG en la vida de las mujeres permea por
completo sus trayectorias vitales.

Tanto en la adolescencia como en la adultez está presente la creencia de que los celos son
una expresión de amor, sin embargo, éstos sirven para legitimar acciones violentas y de extremo control por parte de los varones hacia las mujeres. Si bien todas las personas pueden sentir celos, su mitificación, junto a otros rasgos propios del amor romántico presentan consecuencias diferenciales para hombres y mujeres. Sí los celos son considerados como una expresión de amor, entonces las mujeres se ven tendientes a reproducir una posición dependiente, de sometimiento y despersonalización, mientras que a los varones los coloca en posiciones de control, posesión y dominio (Tuana, 2017). Los celos configuran una forma de violencia simbólica que tiene como consecuencia, entre otras cosas, que las mujeres transiten por un proceso de aislamiento y pérdida de autonomía. Bosch (2007), plantea que esta violencia ejercida contra las mujeres por su pareja o ex-pareja sentimental no refiere a incidentes aislados, sino a un patrón de comportamiento ejercido por el varón con el objetivo de ejercer control y lograr el poder sobre su pareja. Al respecto, Bosch (2007, p. 7) sostiene lo siguiente: “Se trata, en definitiva, del reflejo en el marco de la pareja de una situación de abuso de poder, por ello se
ejerce por parte de quienes detentan ese poder (varones), y la sufren quienes se hallan en una posición más vulnerable (mujeres y niños/as)”. Estos mitos del amor romántico (celos, fidelidad, emparejamiento, exclusividad, omnipotencia, matrimonio y perdurabilidad) y otras ideas que se transmiten en los procesos de socialización operan como mecanismos de disciplinamiento para las mujeres y contribuyen a naturalizar la violencia. Según Bosch (2007), los celos aseguran la exclusividad (sólo se puede amar a una persona a la vez) y la fidelidad y suelen usarse para justificar comportamientos egoístas y violentos. El proceso de socialización es diferencial entre varones y mujeres en cuanto a habilidades y responsabilidades y así el amor romántico es también una experiencia generizada (Ferrer y Bosch, 2013). En el cumplimiento de los mandatos de género, la relación de pareja se vuelve para las mujeres el eje central de sus vidas mientras que no lo es para los varones. Bajo este modelo de amor romántico y los mitos que de él se derivan, resulta más difícil para las mujeres en situaciones de violencia basada en género en la pareja poner fin a la relación o buscar ayuda.

> Así, la creencia en que el amor (y la relación de pareja) es lo que da sentido a sus vidas y que romper la pareja, renunciar al amor es un fracaso puede retrasar la decisión de romper o de buscar ayuda; la creencia en que el amor todo lo puede llevaría a considerar (erróneamente) que es posible vencer cualquier dificultad en la relación y/o de cambiar a su pareja (aunque sea un maltratador irredento) lo que llevaría a perseverar en esa relación violenta; considerar que la violencia y el amor son compatibles (o que ciertos comportamientos violentos son una prueba de amor) justificaría los celos, el afán de posesión y/o los comportamientos de control del maltratador como muestra de amor, y
trasladaría la responsabilidad del maltrato a la víctima por no ajustarse a dichos
requerimientos; etc. (Ferrer y Bosch, 2013, p.114).

En la década del 70, autoras como Kate Millet o Shulamith Firestone, postulaban que el
amor era un dispositivo de control sobre las mujeres. Ahmed (2019) retoma esta idea para hablar sobre el carácter disciplinador de la “felicidad”. A partir de “la promesa de la felicidad” y su búsqueda, se esconde una injusta división sexual del trabajo en detrimento de la autonomía de las mujeres y se impone el matrimonio heterosexual y la maternidad como único camino para alcanzar la felicidad.

> La afirmación de que las mujeres son felices y que esta felicidad radica en el trabajo que hacen permite justificar la división del trabajo en función del género, no como un
producto de la naturaleza, la ley o el deber, sino más bien como la expresión de un
anhelo y deseo colectivo. ¿Qué mejor forma de justificar una distribución desigual del
trabajo que afirmando que dicho trabajo hace felices a las personas que lo realizan?
[...]Cualquier desviación de los roles de género, entendidos en términos de que es
preciso entrenar a las mujeres para hacer felices a los hombres, constituye una
desviación de la felicidad común (Ahmed, 2019, p. 124).

Por otro lado, Lagarde (2008) plantea que la violencia contra las mujeres, tiene un
carácter multifactorial y es permeada por otro tipo de violencias relacionadas con el clasismo, al racismo y otras discriminaciones. La autora considera que la violencia se agrava en condiciones de menor escolarización y falta de ciudadanía y desarrollo social de las mujeres. Por lo tanto, como se planteó al inicio de esta tesis es importante incorporar al abordaje de las situaciones de VBG el concepto de interseccionalidad. El término interseccionalidad fue introducido en 1989 por la abogada y afro-feminista Kimberlé Crenshaw para usarlo como: “una herramienta analítica para estudiar, entender y responder cuando el género se cruza con otras identidades y cómo estos cruces contribuyen a experiencias únicas de opresión y privilegio. Se trata, por tanto, de una metodología indispensable para el trabajo en los campos del desarrollo y los derechos humanos” (Women’s Rights in Development, 2004, p. 1). En tal sentido, la interseccionalidad se
refiere a los procesos –complejos, irreducibles, variados y variables– que en cada contexto derivan de la interacción de factores sociales, económicos, políticos, culturales y simbólicos. La interseccionalidad no es sólo la multiplicidad de identidades en la misma persona, sino que debe entenderse como una herramienta analítica para estudiar cómo el género se cruza con otras identidades y genera experiencias particulares de opresión o privilegio (Akotirene, 2018).

Referirnos a mujeres en términos genéricos puede invisibilizar la diversidad, por eso se
debe incorporar la interseccionalidad como herramienta de análisis e intervención estatal para contemplar la situación de especial vulneración en la que se encuentran las mujeres por diversos motivos. Entre ellos su edad (niñas, adolescentes, jóvenes, adultas mayores y ancianas), orientación sexual e identidad de género, situación de discapacidad, origen étnico-racial, el territorio en el que viven o su situación socioeconómica, entre otras.

En este sentido, una de las premisas de esta tesis es que las condiciones materiales de la
vida de las mujeres definen en gran medida su abanico de oportunidades y la capacidad para
ejercer efectivamente sus derechos mediante el acceso a bienes y servicios. Al incorporar el concepto de interseccionalidad al análisis de las situaciones de VBG, se aborda de manera más integral el problema.

## Femicidio / Feminicidio {-}

El asesinato de las mujeres es la forma más radical del dominio de los varones sobre las
mujeres. El término femicide –femicidio en español– fue introducido por Diana Russell y Jane Caputi en 1990 cuando publicaron el artículo “Femicide: Speaking the Unspeakable”. Luego en 1992, Russell publica junto a Jill Radford el libro “Femicide: The Politics of Woman Killing”. Las autoras introdujeron este término para diferenciar los asesinatos de mujeres de los homicidios en general.

Russell y Radford desarrollaron el término a partir de incorporar la perspectiva de género
en el análisis de los asesinatos de mujeres a manos de hombres. Así encontraron que a los
asesinos les motivaba el hecho de castigar a las mujeres que no aceptaban estar sometidas, que no permitían que esos hombres controlaran sus vidas, sus cuerpos y sexualidades (MESECVI, 2008). En esta definición las autoras no sólo incluyen los asesinatos misóginos, es decir, los motivados por el odio hacia las mujeres, sino todos los asesinatos sexistas, que se caracterizan por estar motivados por un sentido de tener derecho o sentido de propiedad sobre el cuerpo de las mujeres (Iribarne, 2016).

Posteriormente, Lagarde tomó esta definición y la resignificó adaptando la traducción al
español: propone usar feminicidio en vez de femicidio. La autora sostiene que el término
femicidio da cuenta de cualquier tipo de asesinato de mujeres no importando cuál sea la causa, ya que significa homicidio de mujeres. Para esta autora el uso de feminicidio en vez de femicidio, permite poner el énfasis en las razones de género que hay por detrás de estos crímenes así como también la impunidad de los asesinos y la falta de protección y acción del Estado (Lagarde, 2008).

> El feminicidio es el genocidio contra mujeres y sucede cuando las condiciones
históricas generan prácticas sociales que permiten atentados violentos contra la
integridad, la salud, las libertades y la vida de niñas y mujeres [...]. Sin embargo, todos tienen en común que las mujeres son usables, prescindibles, maltratables y desechables. Y, desde luego, todos coinciden en su infinita crueldad y son, de hecho, crímenes de odio contra las mujeres (Lagarde, 2008, pp. 215-216).

Tanto Russell y Caputi (1990) como Lagarde (2008) entienden que el femicidio o feminicidio es una violencia extrema dentro del continuo de violencia de género que atenta contra los derechos humanos de las mujeres y niñas. Lagarde (2008), plantea que el feminicidio se forja en la desigualdad estructural entre mujeres y varones y en la subordinación de estas que se sostiene y reproduce mediante la violencia de género. Por su parte, responsabiliza al Estado, ya que entiende que para que ocurran los feminicidios existe un Estado ausente o negligente. 

Otro aporte fundamental para entender los femicidios es el de Rita Segato. Para esta autora el femicidio implica la apropiación del cuerpo de la mujer por el hecho de serlo o no serlo de la manera que se supone debería serlo: dependiente y sometida al varón. El femicidio se produce como castigo por romper la dependencia y la dominación masculina (Segato, 2003 en Otamendi, 2020). Con el asesinato de la mujer, el agresor toma para sí lo que creía poseer (Hernández et al., 2018 en Otamendi, 2020). En estos casos, el femicidio es el fin de años de violencia de género que puede darse como pérdida de control ante la separación o el deseo de la mujer de separarse, y muchas veces el femicida se suicida luego de cometer el crimen. El suicidio posterior al femicidio se vuelve un acto de remordimiento, vergüenza o temor a las consecuencias (Mathews et al., 2008 en Otamendi, 2020).

> Estos casos son denominados suicidios machistas, ya que se originan en la relación de
dominación y dependencia entre la víctima y el victimario. Cuando la víctima de esa
relación busca romperla o amenaza con hacerlo, el agresor pierde el control y busca
recuperarlo de forma violenta. De este modo, el asesinato es una forma de negar la
pérdida (Otamendi, 2020, p. 111).

El suicidio se produce ya que, el sentido de la vida del agresor estaba dado por la
dominación traumática de la mujer y al matarla, su propia vida ya no tiene sentido (Antúnez,2016 en Otamendi, 2020).

Además de estas visiones complementarias de los asesinatos de mujeres por razones de
género, en el protocolo elaborado por ONU-Mujeres y la Oficina del Alto Comisionado de las
Naciones Unidas para los Derechos Humanos (ACNUDH) se define al femicidio como:

> La muerte violenta de mujeres por razones de género, ya sea que tenga lugar dentro de
la familia, unidad doméstica o en cualquier otra relación interpersonal, en la comunidad,
por parte de cualquier persona, o que sea perpetrada o tolerada por el Estado y sus
agentes, por acción u omisión (ONU-Mujeres y ACNUDH, 2014, p. 14).

Es importante puntualizar que en Uruguay, en el Plan de Acción 2016-2019 por una vida
libre de violencia de género, que se analizará más adelante, se toma esta definición.

En esta investigación se utiliza el término feminicidio para dar cuenta de la responsabilidad del Estado en estos crímenes, salvo cuando se hace referencia a la idea de una autora o la normativa uruguaya que utiliza el término femicidio.
